# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd82e36a6307b4ca116e7b1dd677171e9f7c3304bdde0e6c5f184ba0f482e42c9df92b6f23ca019d4fbf10b79ed91b32eae1178d75ce481f92bb15925a60a976

test:
  secret_key_base: a87f4cc245c8ea60ceebf946c7dd008d39b35603de3a8914f5f7a39eb25c44fe5bf4d47542f9697cc9ab9c27b537bf983c3e13df2b262f7f23584bcdfe3c40f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
